# Generated by Django 5.0.6 on 2025-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL компанії'),
        ),
    ]
